import type { ChatMessage, BridgeLanguageMode } from '../types';

export async function sendChatMessage(
  apiKey: string,
  messages: ChatMessage[],
  bridgeMode: BridgeLanguageMode
): Promise<string> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key=${apiKey}`;

  let bridgeInstruction = '';
  if (bridgeMode === 'german_only') {
    bridgeInstruction = 'STRICT IMMERSION MODE: Reply in 100% German. Never use English or Darija.';
  } else if (bridgeMode === 'german_darija') {
    bridgeInstruction = 'STRICT DARIJA BRIDGE: Reply primarily in German, and explain concepts using Moroccan Darija. STRICTLY FORBIDDEN from using English.';
  } else {
    bridgeInstruction = 'STRICT ENGLISH BRIDGE: Reply primarily in German, and explain concepts using English. STRICTLY FORBIDDEN from using Darija or Arabic.';
  }

  const systemInstruction = `You are LADA, Bilal's brilliant, witty German acquisition companion.
${bridgeInstruction}
Focus on practical vocabulary, compound word breakdowns, natural sentences, and constructive conversational feedback. Keep responses concise, clear, and engaging. Format with clean markdown.`;

  // Format turns for Gemini REST API
  const contents = messages.map(m => ({
    role: m.role === 'user' ? 'user' : 'model',
    parts: [{ text: m.text }]
  }));

  const payload = {
    contents,
    systemInstruction: {
      parts: [{ text: systemInstruction }]
    },
    generationConfig: {
      temperature: 0.7,
      maxOutputTokens: 800
    }
  };

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Gemini API error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error('No response text generated by Gemini.');
  }

  return text;
}
